const THEMES = [
  {
    name: "default",
    hostname: "localhost",
    uri: "http://localhost:3000",
    thumbnails: true,
  },
  {
    name: "yz-test",
    hostname: "test.app.yz-network.com",
    uri: "https://test.app.yz-network.com",
    dark: true,
    dir: "yz",
    project: "YZ",
    thumbnails: true,
  },
  {
    name: "yz",
    hostname: "app.yz-network.com",
    uri: "https://app.yz-network.com",
    dark: true,
    project: "YZ",
    thumbnails: true,
  },
  {
    name: "cdk",
    hostname: "claim.cdktoken.io",
    uri: "https://cdktoken.io",
    title: "CDK Token",
    project: "CDK",
    brand: true,
    favicon: true,
    thumbnails: true,
  },
];
